---

- name: Configure wifi private network
  become: True
  community.general.nmcli:
    type: wifi
    conn_name: "WIFILAN01"
    ifname: "wlan0"
    ssid: "TP-Link_F710"
    dns4:
      - "8.8.8.8"
      - "8.8.4.4"
    wifi_sec:
      psk: 69528132
      key-mgmt: wpa-psk
    wifi:
      powersave: 2
    autoconnect: true
    method4: manual
    ip4:
      - "192.168.0.2/24"  # Subnet mask may be required
    gw4: "192.168.0.1"
    state: present  # Corrected placement of the state parameter

- name: Restart network service  
  become: True
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

