---
- name: Stop services
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: [cliente, display]
  ignore_errors: yes

- name: Remove existing venv directory
  file:
    path: /home/angel/venv
    state: absent
    owner: angel
    group: angel
  when: entorno_python | default(false) | bool

- name: Create Python virtual environment
  command: /usr/bin/python3 -m venv /home/angel/venv
  when: entorno_python | default(false) | bool

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: "/home/angel/lgptclient/requirements_{{ inventory_hostname  }}.txt"
    dest: /home/angel/requirements.txt
    owner: angel
    group: angel
  when: entorno_python | default(false) | bool

- name: Install Python dependencies
  pip:
    requirements: /home/angel/requirements.txt
    virtualenv: /home/angel/venv
    extra_args: "--cache-dir /home/angel/.pip-cache"
  when: entorno_python | default(false) | bool

- name: Sync client files
  synchronize:
    src: /home/angel/lgptclient/bin/cliente_final/
    dest: /home/angel/bin/
    delete: yes
    rsync_opts:
      - "--chown=angel:angel"

- name: Copy client configuration
  ansible.builtin.copy:
    src: "/home/angel/lgptclient/bin/cliente.{{ inventory_hostname  }}.json"
    dest: /home/angel/bin/config.json
    owner: angel
    group: angel

- name: Generate image binary files locally
  ansible.builtin.command:
    cmd: "/home/angel/lgptclient/venv/bin/python /home/angel/lgptclient/bin/genera.py {{ inventory_hostname }}"
  delegate_to: localhost
  when: imagenes | default(false) | bool

- name: Sync image binary files
  synchronize:
    src: "/home/angel/lgptclient/img_output/{{ inventory_hostname }}/"
    dest: /home/angel/images/
    delete: yes
    rsync_opts:
      - "--chown=angel:angel"
  when: imagenes | default(false) | bool

- name: Configure cliente service
  become: true
  template:
    src: cliente.service.j2
    dest: /etc/systemd/system/cliente.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start the cliente service
  become: true
  systemd:
    name: cliente.service
    enabled: yes
    state: started
    daemon_reload: yes