---
- name: Stop cliente service
  become: true
  service:
    name: cliente
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Stop display service
  become: true
  service:
    name: display
    state: stopped
    enabled: no
  ignore_errors: yes  

- name: Remove existing venv directory
  file:
    path: /home/angel/venv
    state: absent
    owner: angel
    group: angel
  when: entorno_python | default(false) | bool

- name: Create Python virtual environment
  command: /usr/bin/python3 -m venv /home/angel/venv
  when: entorno_python | default(false) | bool

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: "/home/angel/lgptclient/requirements_{{ inventory_hostname  }}.txt"
    dest: /home/angel/requirements.txt
    owner: angel
    group: angel
  when: entorno_python | default(false) | bool

- name: Install Python dependencies
  pip:
    requirements: /home/angel/requirements.txt
    virtualenv: /home/angel/venv
  when: entorno_python | default(false) | bool

- name: Remove bin directory
  become: true
  file:
    path: /home/angel/bin/
    state: absent

- name: Create bin directory
  file:
    path: /home/angel/bin/
    state: directory
    owner: angel
    group: angel
    mode: '0755'

- name: Copy client files
  ansible.builtin.copy:
    src: /home/angel/lgptclient/bin/clientet/
    dest: /home/angel/bin/
    owner: angel
    group: angel

- name: Copy client configuration
  ansible.builtin.copy:
    src: "/home/angel/lgptclient/bin/cliente.{{ inventory_hostname  }}.json"
    dest: /home/angel/bin/config.json
    owner: angel
    group: angel

- name: Remove images directory
  file:
    path: /home/angel/images/
    state: absent
    owner: angel
    group: angel
  when: imagenes | default(false) | bool

- name: Create images directory
  ansible.builtin.file:
    state: directory
    path: /home/angel/images/
    owner: angel
    group: angel
  when: imagenes | default(false) | bool

- name: Generate image binary files locally
  local_action:
    module: command
    cmd: "/home/angel/lgptclient/venv/bin/python /home/angel/lgptclient/bin/genera.py {{ inventory_hostname }}"
  when: imagenes | default(false) | bool

- name: Copy image binary files
  copy:
    src: "/home/angel/lgptclient/img_output/{{inventory_hostname}}/"
    dest: /home/angel/images/
    owner: angel
    group: angel
  when: imagenes | default(false) | bool

- name: Configure cliente service
  become: true
  template:
    src: cliente.service.j2
    dest: /etc/systemd/system/cliente.service
    owner: root
    group: root
    mode: '0644'

# - name: Enable and start the cliente service
#   become: true
#   systemd:
#     name: cliente.service
#     enabled: yes
#     state: started
#     daemon_reload: yes