---
- name: Instalamos cliente
  hosts: clientes
  gather_facts: yes
  roles:
    - role: cliente-actualiza
      vars:
        entorno_python: true
        imagenes: true
    - role: servicio-panel
      vars:
        install_python: true