---
- name: Instalamos cliente
  hosts: sombrilla
  gather_facts: yes
  roles:
    - role: cliente-actualiza
      vars:
        entorno_python: false
        imagenes: true
    # - role: servicio-panel
    #   vars:
    #     install_python: false