---
- name: Instalamos maleta
  hosts: clientes
  gather_facts: no
  strategy: free
  roles:
    - role: cliente-actualiza
      vars:
        entorno_python: false
    # - role: servicio-panel
    #   vars:
    #     install_python: false